---
title: "BA 64060 Assignment 1"
author: "Kyle Breeden"
date: "2025-09-07"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import_dataset}
#Use read.csv function to import dataset found on Kaggle.com
#Use readr package for faster and more efficient reading per class slides
#install.packages("readr") #not needed if already installed
library(readr)
assign1_dataset <- read_csv("C:/Users/kylej/OneDrive/Documents/BA 64060/Assignment 1/Data/WA_Fn-UseC_-HR-Employee-Attrition.CSV")
```
```{r}
#Use Spec function to see column specifications
spec(assign1_dataset)
```
```{r}
#Use dplyr package per subsetting data in R reading.
#Select quantitative and categorical variables from the above list to focus on.
library(dplyr)
subset_assign1 <- assign1_dataset %>% 
  select(Age, MonthlyIncome, YearsAtCompany, Attrition, Department, JobRole)
#Then print descriptive stats for the subset
summary(subset_assign1)
```
```{r}
#Use mutate function to transform attrition variable to 0/1
library(dplyr)
subset_assign1 <- subset_assign1 %>% mutate(Attrition = if_else(Attrition== "Yes", 1, 0))
#check to make sure it worked
View(subset_assign1)
```

```{r}
#Use hist function to plot one variable: monthly income
hist(subset_assign1$MonthlyIncome,
     main = "Histogram of Monthly Income",
     xlab = "Monthly Income (USD)")
```
```{r}
#Use plot function to create scatterplot of Age against Monthly Income
plot(subset_assign1$Age, subset_assign1$MonthlyIncome,
     main = "Age vs Monthly Income",
     xlab = "Age (years)",
     ylab = "Monthly Income (USD)")
```
